name: Fetch new feeds and push content to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'feeds.php'
      - 'base.html'
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run feeds.php
        run: php feeds.php

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes if any
        run: |
          git add --all
          git diff --cached --quiet || git commit -m "Update site"

      - name: Push changes
        run: |
          git pull --rebase
          git push origin main

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
